openapi: 3.0.3
info:
  title: Authify
  description: 'Authify Description'
  version: 1.0.0
servers:
  -
    url: 'http://authify.test'
paths:
  /api/v1/register:
    post:
      summary: 'User Registration'
      operationId: userRegistration
      description: 'Daftar pengguna baru dengan nama, nomor telepon, email, dan kata sandi. Verifikasi kode akan dikirim ke nomor telepon.'
      parameters: []
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  user:
                    id: 1
                    name: 'John Doe'
                    phone: '+1234567890'
                    email: john.doe@example.com
                  verification_code: '123456'
                  message: 'A verification code has been sent to your phone.'
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      phone:
                        type: string
                        example: '+1234567890'
                      email:
                        type: string
                        example: john.doe@example.com
                  verification_code:
                    type: string
                    example: '123456'
                  message:
                    type: string
                    example: 'A verification code has been sent to your phone.'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Validation failed'
                  errors:
                    phone:
                      - 'The phone field is required.'
                properties:
                  message:
                    type: string
                    example: 'Validation failed'
                  errors:
                    type: object
                    properties:
                      phone:
                        type: array
                        example:
                          - 'The phone field is required.'
                        items:
                          type: string
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nama pengguna.'
                  example: 'John Doe'
                  nullable: false
                phone:
                  type: string
                  description: 'Nomor telepon dalam format internasional.'
                  example: '+1234567890'
                  nullable: false
                email:
                  type: string
                  description: 'Alamat email pengguna.'
                  example: john.doe@example.com
                  nullable: false
                password:
                  type: string
                  description: 'Kata sandi untuk akun.'
                  example: password123
                  nullable: false
                password_confirmation:
                  type: string
                  description: 'Konfirmasi kata sandi.'
                  example: password123
                  nullable: false
              required:
                - name
                - phone
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: 'User Login'
      operationId: userLogin
      description: 'Masuk dengan nomor telepon dan kata sandi pengguna.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  user:
                    id: 1
                    name: 'John Doe'
                    phone: '+1234567890'
                    email: john.doe@example.com
                  token: eyJhbGciOiJIUzI1NiIsInR5c...
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      phone:
                        type: string
                        example: '+1234567890'
                      email:
                        type: string
                        example: john.doe@example.com
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5c...
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid login credentials'
                properties:
                  message:
                    type: string
                    example: 'Invalid login credentials'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Nomor telepon pengguna yang terdaftar.'
                  example: '+1234567890'
                  nullable: false
                password:
                  type: string
                  description: 'Kata sandi akun pengguna.'
                  example: password123
                  nullable: false
              required:
                - phone
                - password
      security: []
  /api/v1/verify:
    post:
      summary: 'Verify Phone Number'
      operationId: verifyPhoneNumber
      description: 'Verifikasi nomor telepon pengguna menggunakan kode verifikasi yang dikirim.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  user:
                    id: 1
                    name: 'John Doe'
                    phone: '+1234567890'
                    is_verified: true
                  token: eyJhbGciOiJIUzI1NiIsInR5c...
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      phone:
                        type: string
                        example: '+1234567890'
                      is_verified:
                        type: boolean
                        example: true
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5c...
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not found'
                properties:
                  message:
                    type: string
                    example: 'User not found'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid or expired verification code'
                properties:
                  message:
                    type: string
                    example: 'Invalid or expired verification code'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Nomor telepon pengguna.'
                  example: '+1234567890'
                  nullable: false
                code:
                  type: string
                  description: 'Kode verifikasi 6 digit.'
                  example: '123456'
                  nullable: false
              required:
                - phone
                - code
      security: []
  /api/v1/set-new-password:
    post:
      summary: 'Set New Password'
      operationId: setNewPassword
      description: 'Atur ulang kata sandi pengguna menggunakan kode verifikasi.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Password reset successfully'
                properties:
                  message:
                    type: string
                    example: 'Password reset successfully'
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Invalid or expired verification code'
                properties:
                  message:
                    type: string
                    example: 'Invalid or expired verification code'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Nomor telepon pengguna.'
                  example: '+1234567890'
                  nullable: false
                code:
                  type: string
                  description: 'Kode verifikasi 6 digit.'
                  example: '123456'
                  nullable: false
                password:
                  type: string
                  description: 'Kata sandi baru.'
                  example: newpassword123
                  nullable: false
                password_confirmation:
                  type: string
                  description: 'Konfirmasi kata sandi baru.'
                  example: newpassword123
                  nullable: false
              required:
                - phone
                - code
                - password
                - password_confirmation
      security: []
  /api/v1/reset-password:
    post:
      summary: 'Request Password Reset'
      operationId: requestPasswordReset
      description: 'Kirim kode verifikasi untuk mengatur ulang kata sandi pengguna.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Password reset verification code sent'
                  verification_code: '123456'
                properties:
                  message:
                    type: string
                    example: 'Password reset verification code sent'
                  verification_code:
                    type: string
                    example: '123456'
        404:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'User not found'
                properties:
                  message:
                    type: string
                    example: 'User not found'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'Nomor telepon pengguna yang terdaftar.'
                  example: '+1234567890'
                  nullable: false
              required:
                - phone
      security: []
  /api/v1/logout:
    post:
      summary: 'User Logout'
      operationId: userLogout
      description: 'Keluar dari sistem dengan menghapus token akses pengguna.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Logged out successfully'
                properties:
                  message:
                    type: string
                    example: 'Logged out successfully'
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'An error occurred during logout.'
                properties:
                  message:
                    type: string
                    example: 'An error occurred during logout.'
      tags:
        - Authentication
  /api/v1/profile:
    get:
      summary: 'Get User Profile'
      operationId: getUserProfile
      description: 'Ambil detail profil pengguna yang sedang masuk.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  user:
                    id: 1
                    name: 'John Doe'
                    phone: '+1234567890'
                    email: john.doe@example.com
                properties:
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'John Doe'
                      phone:
                        type: string
                        example: '+1234567890'
                      email:
                        type: string
                        example: john.doe@example.com
      tags:
        - 'User Management'
  /api/v1/profile/update:
    post:
      summary: 'Update User Profile'
      operationId: updateUserProfile
      description: 'Perbarui informasi profil pengguna.'
      parameters: []
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Profile updated successfully'
                  user:
                    id: 1
                    name: 'Jane Doe'
                    phone: '+1234567890'
                    email: john.doe@example.com
                properties:
                  message:
                    type: string
                    example: 'Profile updated successfully'
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 1
                      name:
                        type: string
                        example: 'Jane Doe'
                      phone:
                        type: string
                        example: '+1234567890'
                      email:
                        type: string
                        example: john.doe@example.com
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Validation failed'
                  errors:
                    name:
                      - 'The name field is required.'
                properties:
                  message:
                    type: string
                    example: 'Validation failed'
                  errors:
                    type: object
                    properties:
                      name:
                        type: array
                        example:
                          - 'The name field is required.'
                        items:
                          type: string
      tags:
        - 'User Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Nama baru pengguna.'
                  example: 'Jane Doe'
                  nullable: false
              required:
                - name
tags:
  -
    name: Authentication
    description: ''
  -
    name: 'User Management'
    description: ''
