openapi: 3.0.3
info:
  title: Authify
  description: 'Authify Description'
  version: 1.0.0
servers:
  -
    url: 'http://authify.test'
paths:
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the user. Must be at least 2 characters. Must not be greater than 50 characters.'
                  example: 'John Doe'
                  nullable: false
                phone:
                  type: string
                  description: 'The phone number of the user in international format. Must match the regex /^\+\d{10,15}$/.'
                  example: '+1234567890'
                  nullable: false
                email:
                  type: string
                  description: 'The email address of the user. Must be a valid email address.'
                  example: john.doe@example.com
                  nullable: false
                password:
                  type: string
                  description: 'The password for the user account. Must be at least 6 characters.'
                  example: password123
                  nullable: false
              required:
                - name
                - phone
                - email
                - password
      security: []
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'The registered phone number of the user. Must match the regex /^\+\d{10,15}$/. The <code>phone</code> of an existing record in the users table.'
                  example: '+1234567890'
                  nullable: false
                password:
                  type: string
                  description: 'The password for the user account.'
                  example: password123
                  nullable: false
              required:
                - phone
                - password
      security: []
  /api/v1/verify:
    post:
      summary: ''
      operationId: postApiV1Verify
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'The phone number of the user to verify. Must match the regex /^\+\d{10,15}$/. The <code>phone</code> of an existing record in the users table.'
                  example: '+1234567890'
                  nullable: false
                code:
                  type: string
                  description: 'The 6-digit verification code sent to the user. Must be 6 digits. Must be 6 characters.'
                  example: '123456'
                  nullable: false
              required:
                - phone
                - code
      security: []
  /api/v1/set-new-password:
    post:
      summary: ''
      operationId: postApiV1SetNewPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'The registered phone number of the user. Must match the regex /^\+\d{10,15}$/. The <code>phone</code> of an existing record in the users table.'
                  example: '+1234567890'
                  nullable: false
                code:
                  type: string
                  description: 'The 6-digit verification code sent to the user. Must be 6 digits. Must be 6 characters.'
                  example: '123456'
                  nullable: false
                password:
                  type: string
                  description: 'The new password for the user account. Must be at least 6 characters.'
                  example: newpassword123
                  nullable: false
              required:
                - phone
                - code
                - password
      security: []
  /api/v1/reset-password:
    post:
      summary: ''
      operationId: postApiV1ResetPassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: string
                  description: 'The registered phone number of the user to reset the password for. Must match the regex /^\+\d{10,15}$/. The <code>phone</code> of an existing record in the users table.'
                  example: '+1234567890'
                  nullable: false
              required:
                - phone
      security: []
  /api/v1/logout:
    post:
      summary: ''
      operationId: postApiV1Logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/profile:
    get:
      summary: ''
      operationId: getApiV1Profile
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/profile/update:
    post:
      summary: ''
      operationId: postApiV1ProfileUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: quos
                  nullable: false
              required:
                - name
      security: []
tags:
  -
    name: Endpoints
    description: ''
